### ISSUE TITLE
Error deploying SolR service

### ISSUE THREAD

**Issue by Droogy** [docintelapp/DocIntel#3] opened 2022-10-18 16:06 UTC
I tried this on two brand new Linux machines (Ubuntu 22.04 and Debian 10) and I'm getting the same error each time when trying to run the set-up script as shown below. Any suggestions?

"Error response from daemon: Container <id> is not running"

![image](https://user-images.githubusercontent.com/63867669/196483905-9b68e81b-c7b4-4dfb-870b-8054968071f9.png)

**Comment by silvian-io** [comment] 2022-10-18 16:08
Same issue as #2

**Comment by ancailliau** [comment] 2022-10-18 17:00
Closed as duplicate of #2.

**Closed by ancailliau** 2022-10-18 17:00 UTC
